experiment_name: bird_classification_test_Certhia

hydra:
  run:
    dir: ./logs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: ${experiment_name}

# Training parameters
training:
  batch_size: 16 # da aumentare poi
  epochs: 10
  patience: 10
  min_delta: 0.001
  seed: 42
  
# Model configuration
model:
  _target_: models.Improved_Phi_GRU_ATT
  num_classes: 4
  n_mel_bins: 64
  hidden_dim: 32
  n_fft: 400
  hop_length: 160
  matchbox:
    base_filters: 32
    num_layers: 3
    kernel_size: 3
    stride: 1
    dropout: 0.1
  export_mode: false

# Optimizer configuration
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-4

# Learning rate scheduler
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 5
  verbose: true

# Dataset configuration
dataset:
  bird_data_dir: "bird_sound_dataset" # Assicurati che esista e contenga Certhia_familiaris/
  esc50_dir: "ESC-50-master"
  download_datasets: true
  
  sample_rate: 22050
  clip_duration: 3.0
  lowcut: 2000
  highcut: 10000
  
  bird_to_background_ratio: 2.0
  validation_split: 0.15
  test_split: 0.15
  
  load_pregenerated_no_birds: true
  pregenerated_no_birds_dir: "augmented_dataset/no_birds/" 
  num_no_bird_samples: 800 
  esc50_no_bird_ratio: 0.5
  
  extract_calls: true
  min_peak_distance: 1.0
  height_percentile: 75
  
  augmentation:
    enabled: true
    noise_level: 0.005
    time_mask_param: 20
    freq_mask_param: 10
    time_shift_limit: 0.2
    speed_perturb_rate_min: 0.9
    speed_perturb_rate_max: 1.1
    
  allowed_bird_classes: [
    "Certhia_familiaris",
    "Bubo_bubo",
    "Poecile_montanus",
  ] 