experiment_name: 4birds_CF_combined_log_linear_gru64_30epochs # Name for the experiment, used for logging directories

hydra:
  run:
    dir: ./logs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S} # Output directory for logs, organized by experiment name and timestamp
  job:
    name: ${experiment_name} # Job name, defaults to experiment_name

# Training parameters
training:
  batch_size: 32 # Number of samples per batch during training and evaluation
  epochs: 30 # Total number of training epochs
  patience: 4 # Number of epochs with no improvement after which training will be stopped (for early stopping)
  min_delta: 0.001 # Minimum change in the monitored quantity to qualify as an improvement (for early stopping)
  seed: 42 # Random seed for reproducibility
  
# Model configuration
model:
  _target_: models.Improved_Phi_GRU_ATT # Specifies the model class to instantiate
  spectrogram_type: "combined_log_linear" # 'mel', 'linear_stft', 'linear_triangular', or 'combined_log_linear', 
  num_classes: 5 # Total number of output classes (bird species + "non-bird" class)
  n_mel_bins: 64 # Number of Mel frequency bins (used if spectrogram_type is "mel")
  n_linear_filters: 64 # Number of linear triangular filters (used if spectrogram_type is "linear_triangular")
  # f_min and f_max for mel/linear_triangular spectrograms are typically taken from dataset.lowcut and dataset.highcut
  hidden_dim: 64 # GRU hidden dimension
  n_fft: 1024 # Size of the FFT window for spectrogram generation (e.g., 1024 for 32ms window at 32kHz)
  hop_length: 320 # Hop length (stride) for spectrogram generation (e.g., 320 for 10ms hop at 32kHz)
  matchbox: # Configuration for the MatchboxNetSkip CNN backbone
    # input_features will be dynamically set by the model based on spectrogram_type
    # For linear_stft, it will be n_fft // 2 + 1 = 513
    # For mel or linear_triangular, it would be n_mel_bins or n_linear_filters respectively
    base_filters: 32 # Number of filters in the initial conv block and subsequent blocks
    num_layers: 3 # Number of MatchboxNet blocks (each block has 2 sub-blocks, B=3 in paper)
    kernel_size: 5 # Kernel size for depthwise conv in MatchboxNet blocks (K=5 in paper)
    stride: 1 # Stride for MatchboxNet blocks
    dropout: 0.05 # Dropout within MatchboxNet blocks
    breakpoint: 4000 # (Hz) Initial breakpoint for log-linear transition in differentiable filterbank
    transition_width: 100 # Initial transition width (smoothness) for log-linear transition
  export_mode: false # Set to true if exporting model to ONNX, expects spectrograms as input

# Optimizer configuration
optimizer:
  _target_: torch.optim.AdamW # Optimizer class
  lr: 1e-3 # Learning rate
  weight_decay: 1e-4 # Weight decay for regularization

# Learning rate scheduler configuration
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau # Scheduler class
  mode: min # "min" for loss, "max" for accuracy
  factor: 0.5 # Factor by which LR is reduced
  patience: 3 # Epochs to wait for improvement before reducing LR
  verbose: true # Print message when LR is updated

# Dataset configuration
dataset:
  bird_dataset_config:
    _target_: datasets.BirdSoundDataset
  bird_data_dir: "bird_sound_dataset" # Path to bird sound recordings
  esc50_dir: "ESC-50-master" # Path to ESC-50 dataset
  download_datasets: true # Attempt to download ESC-50 if not found
  sample_rate: 32000 # Target sample rate in Hz
  clip_duration: 3.0 # Duration of audio clips in seconds
  lowcut: 150 # Lowcut frequency for bandpass filter and f_min for Mel
  highcut: 16000 # Highcut frequency for bandpass filter and f_max for Mel
  bird_to_background_ratio: 2.0 # Ratio for mixing with background noise (SNR is main control)
  validation_split: 0.15 # Proportion for validation set
  test_split: 0.15 # Proportion for test set
  load_pregenerated_no_birds: true # Load "no birds" from disk or generate on-the-fly
  pregenerated_no_birds_dir: "augmented_dataset/no_birds/" # Directory for pre-generated "no birds"
  num_no_bird_samples: 800 # Target for "no birds" if generated, or max to load if pregenerated & dynamic balancing active
  esc50_no_bird_ratio: 0.5 # Proportion of on-the-fly "no birds" from ESC-50
  extract_calls: true # Extract bird call segments or use random clips
  min_peak_distance: 1.0 # Min seconds between peaks for call extraction
  height_percentile: 75 # Percentile for peak amplitude filtering

  augmentation:
    enabled: true # Enable/disable on-the-fly augmentation
    noise_level: 0.005 # Gaussian noise amplitude
    time_mask_param: 20 # Max time steps for time masking
    freq_mask_param: 10 # Max freq bins for frequency masking
    time_shift_limit: 0.2 # Max proportion for time shifting
    speed_perturb_rate_min: 0.9 # Min rate for speed perturbation
    speed_perturb_rate_max: 1.1 # Max rate for speed perturbation

  allowed_bird_classes:
    - "Bubo_bubo"
    - "Certhia_familiaris"
    - "Poecile_montanus"
    - "Apus_apus"
    # "non-bird" is added automatically
